#!/usr/bin/env bash

set -euo pipefail
# makedeps=(git base-devel)
packages=(
    steam-native-runtime
    glew1.10
    gtk2
    libjpeg6-turbo
    libgcrypt15
    libidn11
    libpng12
    libtiff4
    libudev0-shim
    libvpx1.3
    lib32-glew1.10
    lib32-gtk2
    lib32-libgcrypt15
    lib32-libidn11
    lib32-libindicator-gtk2
    lib32-libpng12
    lib32-librtmp0
    lib32-libtiff4
    lib32-libudev0-shim
    lib32-libvpx1.3
    lib32-libjpeg6-turbo
)
mkdir -p "$(dirname "$0")"/build
cd "$(dirname "$0")"/build
for package in "${packages[@]}"; do
    if [ ! -d "$package" ]; then
        git clone "https://aur.archlinux.org/$package.git"
    else
        (cd "$package" && git pull)
    fi
    (cd "$package" && makepkg -si --noconfirm --needed) || \
    echo "[$(date +"%F %T")] Failed to build «$package»" >> ../build.log && \
    continue # --rmdeps
done
