#!/usr/bin/env bash

set -euo pipefail
# makedeps=(git base-devel)
packages=(
    # steam-runtime libs
    glew1.10
    gtk2
    libjpeg6-turbo
    libgcrypt15
    libidn11
    libindicator-gtk2
    libpng12
    librtmp0
    libtiff4
    libudev0-shim
    libvpx1.3
    openssl-1.0
    lib32-glew1.10
    lib32-gtk2
    lib32-libgcrypt15
    lib32-libdbusmenu-gtk2
    lib32-libidn11
    lib32-libappindicator-gtk2
    lib32-libindicator-gtk2
    lib32-libpng12
    lib32-librtmp0
    lib32-libtiff4
    lib32-libudev0-shim
    lib32-libvpx1.3
    lib32-libjpeg6-turbo
    lib32-openssl-1.0
)
packages+=(steam-native-runtime)
basedir="$(realpath "$(dirname "$0")")"
[ ! -d build ] && "$basedir"/build
if [ ! -d logs ]; then
    mkdir "$basedir"/logs
else
    rm "$basedir/logs/"*.log
fi
cd "$basedir"/build
for package in "${packages[@]}"; do
    echo "Working on «$package»"
    if [ ! -d "$package" ]; then
        git clone "https://aur.archlinux.org/$package.git"
    else
        cd "$basedir/build/$package"
        git pull > /dev/null
    fi
    cd "$basedir/build/$package"
    makepkg -si --noconfirm --needed --asdeps > "$basedir/logs/$package.log" 2>&1 || \
    echo "[$(date +"%F %T")] Failed to build «$package»" >> "$basedir/build.log" && \
    continue # --rmdeps
done
