#!/usr/bin/env bash

set -euo pipefail

opt=${1:-""}

find \
    build/ \
    -maxdepth 2 \
    -name "*.pkg.tar.zst" \
    -exec rm {} \;

if [ "$opt" == "-f" ]; then
    for d in build/*; do
        rm -rf "$d/src"
        rm -rf "$d/pkg"
    done
fi
