#!/usr/bin/env bash

docker run --rm -it \
  -e XDG_CONFIG_HOME=/config \
  -v /var/cache/pacman/pkg:/var/cache/pacman/pkg \
  -v "$XDG_CONFIG_HOME/pacman/makepkg.conf":/config/pacman/makepkg.conf \
  -v "$(realpath "$(dirname "$0")")":/workspace \
  -w /workspace \
  archlinux:multilib-devel \
  bash -c "
  groupadd -g $(id -g) $(id -gn);
  useradd -m -u $(id -u) -g $(id -g) $(id -un)
  pacman -Sy --noconfirm git;
  echo '$(id -un) ALL=(ALL) NOPASSWD: /usr/bin/pacman' > /etc/sudoers.d/$(id -un)
  su -s /bin/bash $(id -un) -c ./build-packages
  "
