#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

[ ! -d build/ ] && echo "No build/ directory" && exit 1
arch=x86_64
find \
    build/ \
    -maxdepth 2 \
    -name "*-$arch.pkg.tar.zst" \
    -exec cp {} $arch/ \;

repo-add \
    --quiet \
    --remove \
    $arch/steam-libs.db.tar.gz \
    $arch/*.pkg.tar.zst
