#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

arch=x86_64
find \
    build/ \
    -maxdepth 2 \
    -name "*-$arch.pkg.tar.zst" \
    -exec cp {} $arch/ \;

repo-add \
    --quiet \
    --remove \
    $arch/steam-libs.db.tar.gz \
    $arch/*.pkg.tar.zst
